global:
  jobKind: CronJob
  enableKeyVaults: true
  tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"
job:
  releaseNameOverride: "{{ .Release.Name }}-crons"
  disableActiveClusterCheck: true
  image: hmctspublic.azurecr.io/cath/cath-crons:latest
  aadIdentityName: cath
  environment:
    NODE_ENV: 'production'
    SCRIPT_NAME: 'example'
  keyVaults:
    pip-ss-kv:
      secrets:
        - name: app-insights-connection-string
          alias: APPLICATION_INSIGHTS_CONNECTION_STRING
        - name: db-url
          alias: DATABASE_URL
  schedule: "0 0/10 * * *" # this is just a placeholder, configure in your flux
  concurrencyPolicy: Forbid
