nodejs:
  releaseNameOverride: "{{ .Release.Name }}-postgres"
  applicationPort: 5555
  aadIdentityName: cath
  ingressHost: cath-postgres.{{ .Values.global.environment }}.platform.hmcts.net
  image: 'hmctspublic.azurecr.io/cath/cath-postgres:latest'
  environment:
    POSTGRES_DATABASE: cath
  keyVaults:
    pip-ss-kv:
      secrets:
        - name: postgres-url
          alias: DATABASE_URL
