# Local Development Helm Values
# This file is used for local development only
# See values.yaml for production configuration

nodejs:
  keyVaults:
    pip-ss-kv-stg:
      secrets:
        - name: app-tenant-id
          alias: AZURE_TENANT_ID
        - name: app-pip-data-management-id
          alias: AZURE_CLIENT_ID
        - name: app-pip-data-management-scope
          alias: AZURE_SCOPE
